-- SQL to create tables
CREATE TABLE "OPTQUERYDATA"
(
"QUERY_ID" INT not null primary key
        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),
"PANEL_NO" VARCHAR(50),   
"SUBJECT" VARCHAR(1000),
"QUESTION" VARCHAR (10000),

"ANSWER" VARCHAR(50),
"STATUS" VARCHAR(10000)

);


